trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  VERACODE_API_KEY_ID: $(VERACODE_API_KEY_ID)
  VERACODE_API_KEY_SECRET: $(VERACODE_API_KEY_SECRET)

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
    displayName: 'Use Python 3.x'

  - script: |
      echo "Updating package lists..."
      sudo apt-get update -y

      echo "Installing required system dependencies..."
      sudo apt-get install -y python3 python3-pip curl unzip

      echo "Installing Veracode API Signing Library and HTTPie..."
      pip install --upgrade httpie httpie-hmac-auth veracode-api-signing requests

      echo "Verifying installation..."
      python3 --version
      pip list | grep -E 'httpie|veracode-api-signing'

      echo "Testing Veracode API Connectivity..."
      http --auth-type=veracode_hmac --ignore-stdin "https://analysiscenter.veracode.com/api/5.0/getapplist.do"
    displayName: 'Check Veracode API Connectivity'
    env:
      VERACODE_API_KEY_ID: $(VERACODE_API_KEY_ID)
      VERACODE_API_KEY_SECRET: $(VERACODE_API_KEY_SECRET)
