trigger:
  - master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo "Installing httpie and HMAC plugin..."
    pip install --upgrade httpie httpie-hmac-auth

    echo "Testing Veracode API Connectivity..."
    http --auth-type=veracode_hmac --ignore-stdin "https://analysiscenter.veracode.com/api/5.0/getapplist.do"
  displayName: 'Test Veracode API Connectivity'
  env:
    VERACODE_API_KEY_ID: $(VERACODE_API_KEY_ID)
    VERACODE_API_KEY_SECRET: $(VERACODE_API_KEY_SECRET)
