trigger:
  - master  # Adjust to your desired branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  VERACODE_API_KEY_ID: $(VID)  # Set these in Azure DevOps pipeline secrets
  VERACODE_API_KEY_SECRET: $(VKEY)
  TARGET_URL: "https://juice-shop.herokuapp.com/#/"  # Replace with your target URL
  ANALYSIS_NAME: "DynamicAnalysis-$(Build.BuildId)"  # Unique analysis name

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
    displayName: 'Use Python 3.x'

  - script: |
      echo "========================================"
      echo " Step 1: Installing Dependencies"
      echo "========================================"
      sudo apt-get update -y
      sudo apt-get install -y python3 python3-pip curl jq
      pip install --upgrade httpie httpie-hmac-auth veracode-api-signing requests

      echo "========================================"
      echo " Step 2: Verifying Installations"
      echo "========================================"
      python3 --version
      pip list | grep -E 'httpie|veracode-api-signing'
    displayName: 'Install Dependencies'

  - script: |
      echo "========================================"
      echo " Step 3: Validating API Credentials"
      echo "========================================"

      if [[ -z "$VERACODE_API_KEY_ID" ]]; then
        echo "❌ ERROR: VERACODE_API_KEY_ID is not set!"
        exit 1
      fi

      if [[ -z "$VERACODE_API_KEY_SECRET" ]]; then
        echo "❌ ERROR: VERACODE_API_KEY_SECRET is not set!"
        exit 1
      fi

      echo "✅ Veracode API Credentials are set!"
    displayName: 'Validate API Credentials'
    env:
      VERACODE_API_KEY_ID: $(VERACODE_API_KEY_ID)
      VERACODE_API_KEY_SECRET: $(VERACODE_API_KEY_SECRET)

  - script: |
      echo "========================================"
      echo " Step 4: Creating Veracode Dynamic Analysis"
      echo "========================================"

      analysis_payload=$(cat <<EOF
      {
        "name": "$ANALYSIS_NAME",
        "scans": [
          {
            "scan_config_request": {
              "target_url": {
                "url": "$TARGET_URL"
              }
            }
          }
        ],
        "schedule": {
          "duration": {
            "length": 1,
            "unit": "DAY"
          },
          "now": true,
          "schedule_status": "ACTIVE"
        }
      }
      EOF
      )

      echo "Payload Sent: $analysis_payload"

      response=$(http --auth-type=veracode_hmac \
        POST "https://api.veracode.com/was/configservice/v1/analyses" \
        Content-Type:application/json \
        <<< "$analysis_payload")

      echo "API Response: $response"

      analysis_id=$(echo "$response" | jq -r '.analysis_id')

      if [[ -z "$analysis_id" || "$analysis_id" == "null" ]]; then
        echo "❌ Error: Failed to trigger Dynamic Analysis"
        exit 1
      fi

      echo "✅ Triggered Veracode Dynamic Analysis with ID: $analysis_id"
      echo "##vso[task.setvariable variable=ANALYSIS_ID]$analysis_id"
    displayName: 'Trigger Veracode Dynamic Analysis'
    env:
      VERACODE_API_KEY_ID: $(VERACODE_API_KEY_ID)
      VERACODE_API_KEY_SECRET: $(VERACODE_API_KEY_SECRET)