trigger:
  - master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo "Testing Veracode API Connectivity using cURL..."
    curl -H "Authorization: VERACODE-HMAC" \
         -H "User-Agent: AzureDevOpsPipeline" \
         --user "$VERACODE_API_KEY_ID:$VERACODE_API_KEY_SECRET" \
         "https://analysiscenter.veracode.com/api/5.0/getapplist.do"
  displayName: 'Test Veracode API Connectivity with cURL'
  env:
    VERACODE_API_KEY_ID: $(VERACODE_API_KEY_ID)
    VERACODE_API_KEY_SECRET: $(VERACODE_API_KEY_SECRET)