trigger:
  - master  # Change to your branch if needed

pool:
  vmImage: 'ubuntu-latest'

variables:
  VID: $(VID)  # Fetch from Azure DevOps secrets
  VKEY: $(VKEY)
  TARGET_URL: "https://c628-2001-8f8-1761-1599-6839-8b3a-2c59-5ea4.ngrok-free.app/"  # Replace with your live API URL

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
    displayName: 'Use Python 3.x'

  - script: |
      echo "========================================"
      echo " Step 1: Installing Dependencies"
      echo "========================================"
      sudo apt-get update -y
      sudo apt-get install -y python3 python3-pip curl jq
      pip install --upgrade httpie httpie-hmac-auth veracode-api-signing requests

      echo "========================================"
      echo " Step 2: Verifying Installations"
      echo "========================================"
      python3 --version
      pip list | grep -E 'httpie|veracode-api-signing'
    displayName: 'Install Dependencies'

  - script: |
      echo "========================================"
      echo " Step 3: Debugging API Credentials"
      echo "========================================"

      echo "VID Variable Length: ${#VID}"
      echo "VKEY Variable Length: ${#VKEY}"

      if [[ -z "$VID" ]]; then
        echo "❌ ERROR: VID (Veracode API Key ID) is not set!"
        exit 1
      fi

      if [[ -z "$VKEY" ]]; then
        echo "❌ ERROR: VKEY (Veracode API Key Secret) is not set!"
        exit 1
      fi

      echo "✅ Veracode API Credentials are set!"
    displayName: 'Check & Debug Environment Variables'
    env:
      VID: $(VID)
      VKEY: $(VKEY)

  - script: |
      echo "========================================"
      echo " Step 4: Testing Veracode API Authentication"
      echo "========================================"

      response=$(http --auth-type=veracode_hmac GET "https://api.veracode.com/was/configservice/v1/api_specifications")

      echo "API Authentication Response: $response"

      if [[ "$response" == *"Unauthorized"* ]]; then
        echo "❌ ERROR: Veracode authentication failed!"
        exit 1
      fi

      echo "✅ Successfully authenticated with Veracode API"
    displayName: 'Test Veracode API Authentication'
    env:
      VID: $(VID)
      VKEY: $(VKEY)

  - script: |
      echo "========================================"
      echo " Step 5: Creating Veracode Dynamic Scan"
      echo "========================================"

      analysis_payload=$(cat <<EOF
      {
        "name": "AzureDevOps-API-DynamicScan",
        "scans": [
          {
            "action_type": "ADD",
            "scan_config_request": {
              "target_url": {
                "url": "$(TARGET_URL)"
              }
            }
          }
        ],
        "schedule": {
          "duration": {
            "length": 2,
            "unit": "DAY"
          },
          "now": true,
          "schedule_status": "ACTIVE"
        }
      }
      EOF
      )

      echo "Payload Sent: $analysis_payload"

      response=$(curl -s -X POST "https://api.veracode.com/was/configservice/v1/analyses?scan_type=API_SCAN" \
      -H "Content-Type: application/json" \
      -H "Authorization: Veracode-HMAC" \
      -u "$VID:$VKEY" \
      -d "$analysis_payload")

      echo "API Response: $response"

      analysis_id=$(echo "$response" | jq -r '.analysis_id')

      if [[ -z "$analysis_id" || "$analysis_id" == "null" ]]; then
        echo "❌ Error: Failed to trigger Dynamic Scan"
        exit 1
      fi

      echo "✅ Triggered Veracode Dynamic Scan with ID: $analysis_id"
      echo "##vso[task.setvariable variable=ANALYSIS_ID]$analysis_id"
    displayName: 'Trigger Veracode Dynamic Scan'
    env:
      VID: $(VID)
      VKEY: $(VKEY)